/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.CardLayout;
import javax.swing.SwingUtilities;
import AppPackage.AnimationClass;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;
/**
 *
 * @author ricar
 */
public class Ventana_principal extends javax.swing.JFrame {

    boolean bot1,bot2,bot3;
    CardLayout card;
    public Ventana_principal() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        bot1=bot2=bot3=false;
        card=(CardLayout)panel_informacion.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_ventana = new javax.swing.JPanel();
        boton1 = new javax.swing.JButton();
        panel_informacion = new javax.swing.JPanel();
        etiqueta_logo = new javax.swing.JLabel();
        etiqueta_usuario = new javax.swing.JLabel();
        etiqueta_iniciar_sension = new javax.swing.JLabel();
        etiqueta_nuevo_usuario = new javax.swing.JLabel();
        etiqueta_bienvenido = new javax.swing.JLabel();
        et_internet = new javax.swing.JLabel();
        et_calculadora = new javax.swing.JLabel();
        et_musica = new javax.swing.JLabel();
        et_minimizar = new javax.swing.JLabel();
        et_salir = new javax.swing.JLabel();
        et_menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panel_ventana.setBackground(new java.awt.Color(255, 255, 255));
        panel_ventana.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        panel_ventana.setForeground(new java.awt.Color(255, 102, 0));
        panel_ventana.setMinimumSize(new java.awt.Dimension(600, 360));
        panel_ventana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton1.setText("jButton1");
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                boton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                boton1MouseExited(evt);
            }
        });
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        panel_ventana.add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 410, 150, 30));

        panel_informacion.setBackground(new java.awt.Color(255, 255, 255));
        panel_informacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        panel_informacion.setForeground(new java.awt.Color(255, 102, 0));
        panel_informacion.setLayout(new java.awt.CardLayout());

        etiqueta_logo.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta_logo.setForeground(new java.awt.Color(204, 204, 204));
        etiqueta_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo-universidad-privada-del-estado-de-mexico_opt (1).png"))); // NOI18N
        panel_informacion.add(etiqueta_logo, "card2");

        panel_ventana.add(panel_informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 430, 460));

        etiqueta_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones 2/icons8_User_96px_2.png"))); // NOI18N
        panel_ventana.add(etiqueta_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 100, 90));

        etiqueta_iniciar_sension.setBackground(new java.awt.Color(255, 102, 0));
        etiqueta_iniciar_sension.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        etiqueta_iniciar_sension.setForeground(new java.awt.Color(255, 102, 0));
        etiqueta_iniciar_sension.setText("Iniciar Sension");
        etiqueta_iniciar_sension.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        etiqueta_iniciar_sension.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiqueta_iniciar_sensionMouseClicked(evt);
            }
        });
        panel_ventana.add(etiqueta_iniciar_sension, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, 30));

        etiqueta_nuevo_usuario.setBackground(new java.awt.Color(255, 102, 0));
        etiqueta_nuevo_usuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        etiqueta_nuevo_usuario.setForeground(new java.awt.Color(255, 102, 0));
        etiqueta_nuevo_usuario.setText("Nuevo Usuario");
        etiqueta_nuevo_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        etiqueta_nuevo_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiqueta_nuevo_usuarioMouseClicked(evt);
            }
        });
        panel_ventana.add(etiqueta_nuevo_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 110, -1));

        etiqueta_bienvenido.setBackground(new java.awt.Color(255, 102, 0));
        etiqueta_bienvenido.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        etiqueta_bienvenido.setForeground(new java.awt.Color(255, 102, 0));
        etiqueta_bienvenido.setText("BIENVENIDO");
        panel_ventana.add(etiqueta_bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 240, -1));

        et_internet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones 2/icons8_Globe_32px.png"))); // NOI18N
        et_internet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                et_internetMouseClicked(evt);
            }
        });
        panel_ventana.add(et_internet, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 50, -1, 30));

        et_calculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones 2/icons8_Calculator_32px.png"))); // NOI18N
        et_calculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                et_calculadoraMouseClicked(evt);
            }
        });
        panel_ventana.add(et_calculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 90, -1, 30));

        et_musica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones 2/icons8_Musical_Notes_32px.png"))); // NOI18N
        et_musica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                et_musicaMouseClicked(evt);
            }
        });
        panel_ventana.add(et_musica, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 130, -1, -1));

        et_minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones 2/icons8_Expand_Arrow_32px.png"))); // NOI18N
        et_minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        et_minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                et_minimizarMouseClicked(evt);
            }
        });
        panel_ventana.add(et_minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, -1, 30));

        et_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones 2/icons8_Multiply_32px.png"))); // NOI18N
        et_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        et_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                et_salirMouseClicked(evt);
            }
        });
        panel_ventana.add(et_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, 30));

        et_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones 2/icons8_Menu_32px.png"))); // NOI18N
        et_menu.setText("jLabel2");
        et_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        et_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                et_menuMouseClicked(evt);
            }
        });
        panel_ventana.add(et_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 40));

        getContentPane().add(panel_ventana, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseExited
        Animacion.Animacion.mover_izquierda(0,-100, 1, 2, boton1);
    }//GEN-LAST:event_boton1MouseExited

    private void boton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseEntered
        if(!bot1)
        {
            Animacion.Animacion.mover_derecha(-100, 0, 1, 2, boton1);
        }
    }//GEN-LAST:event_boton1MouseEntered

    private void etiqueta_iniciar_sensionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiqueta_iniciar_sensionMouseClicked
     iniciar();
    }//GEN-LAST:event_etiqueta_iniciar_sensionMouseClicked

    private void etiqueta_nuevo_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiqueta_nuevo_usuarioMouseClicked
        nuevo();
    }//GEN-LAST:event_etiqueta_nuevo_usuarioMouseClicked

    private void et_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_et_menuMouseClicked
       //etiqueta menu
        AnimationClass internet =new AnimationClass();
       internet.jLabelXRight(-30, 0, 10, 5, et_internet);
        AnimationClass internett =new AnimationClass();
       internett.jLabelXLeft(0, -30, 10, 5, et_internet);
       //etiqueta calculadora
           AnimationClass calcu =new AnimationClass();
       calcu.jLabelXRight(-30, 0, 10, 5, et_calculadora);
        AnimationClass calcuu =new AnimationClass();
       calcuu.jLabelXLeft(0, -30, 10, 5, et_calculadora);
       //etiqueta musica
           AnimationClass music =new AnimationClass();
       music.jLabelXRight(-30, 0, 10, 5, et_musica);
        AnimationClass musicc =new AnimationClass();
       musicc.jLabelXLeft(0, -30, 10, 5, et_musica);
    }//GEN-LAST:event_et_menuMouseClicked

    private void et_minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_et_minimizarMouseClicked
        this.setState(Ventana_principal.ICONIFIED);
    }//GEN-LAST:event_et_minimizarMouseClicked

    private void et_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_et_salirMouseClicked
               int dialog=JOptionPane.YES_NO_OPTION;
               int result=JOptionPane.showConfirmDialog(null,"Deseas salir del programa?","Exit",dialog);
               if(result==0){
                   System.exit(0);
               }
    }//GEN-LAST:event_et_salirMouseClicked

    private void et_internetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_et_internetMouseClicked
        openinternet();
    }//GEN-LAST:event_et_internetMouseClicked

    private void et_calculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_et_calculadoraMouseClicked
        try{
            Runtime rt=Runtime.getRuntime();
            Process p=rt.exec("calc");
            p.waitFor();
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_et_calculadoraMouseClicked

    private void et_musicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_et_musicaMouseClicked
         try{
            Runtime rt=Runtime.getRuntime();
            Process p=rt.exec("");
            p.waitFor();
        }catch(Exception ex){
                 JOptionPane.showConfirmDialog(this, ex);
        }
        
    }//GEN-LAST:event_et_musicaMouseClicked
    public void openinternet()
    {
        try{
            Desktop.getDesktop().browse(URI.create("www.google.com"));
        }catch(Exception ex){
            JOptionPane.showConfirmDialog(this, ex);
        }
    }
    public void iniciar()
    {
        Iniciar_Sesion iniciar_sesion= new Iniciar_Sesion();
        panel_informacion.add(iniciar_sesion,"iniciar_sesion");
        card.show(panel_informacion,"iniciar_sesion");
        SwingUtilities.updateComponentTreeUI(this);
    }
      public void nuevo()
    {
        Nuevo_usuario nuevo_usuario=new Nuevo_usuario();
        panel_informacion.add(nuevo_usuario,"nuevo_usuario");
        card.show(panel_informacion,"nuevo_usuario");
        SwingUtilities.updateComponentTreeUI(this);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JLabel et_calculadora;
    private javax.swing.JLabel et_internet;
    private javax.swing.JLabel et_menu;
    private javax.swing.JLabel et_minimizar;
    private javax.swing.JLabel et_musica;
    private javax.swing.JLabel et_salir;
    private javax.swing.JLabel etiqueta_bienvenido;
    private javax.swing.JLabel etiqueta_iniciar_sension;
    private javax.swing.JLabel etiqueta_logo;
    private javax.swing.JLabel etiqueta_nuevo_usuario;
    private javax.swing.JLabel etiqueta_usuario;
    private javax.swing.JPanel panel_informacion;
    private javax.swing.JPanel panel_ventana;
    // End of variables declaration//GEN-END:variables
}
