/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author ricar
 */
public class Nuevo_usuario extends javax.swing.JPanel {

    /**
     * Creates new form Nuevo_usuario
     */
    public Nuevo_usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        et_usuario = new javax.swing.JLabel();
        et_contraseña = new javax.swing.JLabel();
        et_correo = new javax.swing.JLabel();
        et_nombre = new javax.swing.JLabel();
        et_registro_usuario = new javax.swing.JLabel();
        et_confirmar = new javax.swing.JLabel();
        et_contraseña2 = new javax.swing.JLabel();
        et_dibujito_usuario = new javax.swing.JLabel();
        caja_usuario_nuevo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        caja_contraseña_nuevo = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        caja_confirmacion_nuevo = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        caja_nombre_nuevo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        caja_correo_nuevo = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        boton_enter_nuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        setForeground(new java.awt.Color(255, 102, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        et_usuario.setBackground(new java.awt.Color(255, 102, 0));
        et_usuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        et_usuario.setForeground(new java.awt.Color(255, 102, 0));
        et_usuario.setText("Usuario:");
        add(et_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 55, -1));

        et_contraseña.setBackground(new java.awt.Color(255, 102, 0));
        et_contraseña.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        et_contraseña.setForeground(new java.awt.Color(255, 102, 0));
        et_contraseña.setText("Contraseña:");
        add(et_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 78, -1));

        et_correo.setBackground(new java.awt.Color(255, 102, 0));
        et_correo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        et_correo.setForeground(new java.awt.Color(255, 102, 0));
        et_correo.setText("Correo:");
        add(et_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 50, -1));

        et_nombre.setBackground(new java.awt.Color(255, 102, 0));
        et_nombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        et_nombre.setForeground(new java.awt.Color(255, 102, 0));
        et_nombre.setText("Nombre:");
        add(et_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 50, -1));

        et_registro_usuario.setBackground(new java.awt.Color(255, 102, 0));
        et_registro_usuario.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        et_registro_usuario.setForeground(new java.awt.Color(255, 102, 0));
        et_registro_usuario.setText("Registro De Usuario");
        add(et_registro_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 200, -1));

        et_confirmar.setBackground(new java.awt.Color(255, 102, 0));
        et_confirmar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        et_confirmar.setForeground(new java.awt.Color(255, 102, 0));
        et_confirmar.setText("Confirmar");
        add(et_confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 78, -1));

        et_contraseña2.setBackground(new java.awt.Color(255, 102, 0));
        et_contraseña2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        et_contraseña2.setForeground(new java.awt.Color(255, 102, 0));
        et_contraseña2.setText("Contraseña:");
        add(et_contraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, -1));

        et_dibujito_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios.jpg"))); // NOI18N
        add(et_dibujito_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 60, -1));

        caja_usuario_nuevo.setBackground(new java.awt.Color(255, 255, 255));
        caja_usuario_nuevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        caja_usuario_nuevo.setForeground(new java.awt.Color(0, 0, 0));
        caja_usuario_nuevo.setText("Ingrese su Nombre de Usuario");
        caja_usuario_nuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        caja_usuario_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(caja_usuario_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 180, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 210, 10));

        caja_contraseña_nuevo.setBackground(new java.awt.Color(255, 255, 255));
        caja_contraseña_nuevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        caja_contraseña_nuevo.setForeground(new java.awt.Color(0, 0, 0));
        caja_contraseña_nuevo.setText("+++++++++++++++++++++++++++++++++++++++++++");
        caja_contraseña_nuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        caja_contraseña_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(caja_contraseña_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 180, 30));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 210, -1));

        caja_confirmacion_nuevo.setBackground(new java.awt.Color(255, 255, 255));
        caja_confirmacion_nuevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        caja_confirmacion_nuevo.setForeground(new java.awt.Color(0, 0, 0));
        caja_confirmacion_nuevo.setText("+++++++++++++++++++++++++++++++++++++++++++++");
        caja_confirmacion_nuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        caja_confirmacion_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        caja_confirmacion_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja_confirmacion_nuevoActionPerformed(evt);
            }
        });
        add(caja_confirmacion_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 227, 190, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 210, -1));

        caja_nombre_nuevo.setBackground(new java.awt.Color(255, 255, 255));
        caja_nombre_nuevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        caja_nombre_nuevo.setForeground(new java.awt.Color(0, 0, 0));
        caja_nombre_nuevo.setText("Ingrese su Nombre Completo");
        caja_nombre_nuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        caja_nombre_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(caja_nombre_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 180, 20));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 322, 220, 10));

        caja_correo_nuevo.setBackground(new java.awt.Color(255, 255, 255));
        caja_correo_nuevo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        caja_correo_nuevo.setForeground(new java.awt.Color(0, 0, 0));
        caja_correo_nuevo.setText("Ingrese su Correo Electronico");
        caja_correo_nuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        caja_correo_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(caja_correo_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 200, 20));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 220, 10));

        boton_enter_nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones 2/Enter_OFF.png"))); // NOI18N
        boton_enter_nuevo.setBorder(null);
        boton_enter_nuevo.setBorderPainted(false);
        boton_enter_nuevo.setContentAreaFilled(false);
        boton_enter_nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_enter_nuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones 2/Enter_ON.png"))); // NOI18N
        boton_enter_nuevo.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones 2/Enter_ON.png"))); // NOI18N
        boton_enter_nuevo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones 2/Enter_ON.png"))); // NOI18N
        add(boton_enter_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/email.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 70, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nombre.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/confirmar.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sombrero.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pas.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void caja_confirmacion_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja_confirmacion_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja_confirmacion_nuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_enter_nuevo;
    private javax.swing.JPasswordField caja_confirmacion_nuevo;
    private javax.swing.JPasswordField caja_contraseña_nuevo;
    private javax.swing.JTextField caja_correo_nuevo;
    private javax.swing.JTextField caja_nombre_nuevo;
    private javax.swing.JTextField caja_usuario_nuevo;
    private javax.swing.JLabel et_confirmar;
    private javax.swing.JLabel et_contraseña;
    private javax.swing.JLabel et_contraseña2;
    private javax.swing.JLabel et_correo;
    private javax.swing.JLabel et_dibujito_usuario;
    private javax.swing.JLabel et_nombre;
    private javax.swing.JLabel et_registro_usuario;
    private javax.swing.JLabel et_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
